### ISSUE TITLE
Not compat with scala 2.13.9 and 2.13.10

### ISSUE THREAD

**Issue by djx314** [ThoughtWorksInc/todo#66]
Update scala version to `2.13.9` and `2.13.10` and compile broken.

At first find that `Binding.scala` and `html.scala` is not working, and find this repo. Then set the scala version from `2.13.10` to `2.13.7` and my project now compile successed.

**Comment by djx314** [comment]
sbt:todo> js/compile
[info] compiling 1 Scala source to E:\pro\workspace\desu-video\target\todo\js\target\classes ...
[error] E:\pro\workspace\desu-video\target\todo\js\src\main\scala\com\thoughtworks\todo\Main.scala:63:5: multiple constructors for UnprefixedAttribute with alternatives:
[error]   (key: String,value: Option[scala.collection.Seq[scala.xml.Node]],next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: String,next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: scala.collection.Seq[scala.xml.Node],next1: scala.xml.MetaData)scala.xml.UnprefixedAttribute
[error]  cannot be invoked with (String, org.lrng.binding.html.NodeBindingSeq[org.scalajs.dom.Node], scala.xml.MetaData
[error]     <header class="header">
[error]     ^
[error] E:\pro\workspace\desu-video\target\todo\js\src\main\scala\com\thoughtworks\todo\Main.scala:64:7: type mismatch;
[error]  found   : org.lrng.binding.html.NodeBindingSeq[org.scalajs.dom.Node]
[error]     (which expands to)  com.thoughtworks.binding.Binding.BindingSeq[org.scalajs.dom.raw.Node]{def value: scala.collection.Seq[org.scalajs.dom.raw.Node]}
[error]  required: Seq[scala.xml.Node]
[error]       <h1>todos</h1>
[error]       ^
[error] E:\pro\workspace\desu-video\target\todo\js\src\main\scala\com\thoughtworks\todo\Main.scala:65:7: multiple constructors for UnprefixedAttribute with alternatives:
[error]   (key: String,value: Option[scala.collection.Seq[scala.xml.Node]],next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: String,next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: scala.collection.Seq[scala.xml.Node],next1: scala.xml.MetaData)scala.xml.UnprefixedAttribute
[error]  cannot be invoked with (String, org.scalajs.dom.KeyboardEvent => Unit, scala.xml.MetaData)
[error]       <input class="new-todo" autofocus={true} placeholder="What needs to be done?" onkeydown={keyDownHandler}/
[error]       ^
[error] E:\pro\workspace\desu-video\target\todo\js\src\main\scala\com\thoughtworks\todo\Main.scala:97:21: multiple constructors for UnprefixedAttribute with alternatives:
[error]   (key: String,value: Option[scala.collection.Seq[scala.xml.Node]],next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: String,next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: scala.collection.Seq[scala.xml.Node],next1: scala.xml.MetaData)scala.xml.UnprefixedAttribute
[error]  cannot be invoked with (String, org.scalajs.dom.KeyboardEvent => Any, scala.xml.MetaData)
[error]     val editInput = <input id="editInput" class="edit" value={ todo.title } onblur={ blurHandler.bind } onkeydown={ keyDownHandler } />;
[error]                     ^
[error] E:\pro\workspace\desu-video\target\todo\js\src\main\scala\com\thoughtworks\todo\Main.scala:99:7: multiple constructors for UnprefixedAttribute with alternatives:
[error]   (key: String,value: Option[scala.collection.Seq[scala.xml.Node]],next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: String,next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: scala.collection.Seq[scala.xml.Node],next1: scala.xml.MetaData)scala.xml.UnprefixedAttribute
[error]  cannot be invoked with (String, org.lrng.binding.html.NodeBindingSeq[org.scalajs.dom.Node], scala.xml.MetaData
[error]       <div class="view">
[error]       ^
[error] E:\pro\workspace\desu-video\target\todo\js\src\main\scala\com\thoughtworks\todo\Main.scala:100:9: multiple constructors for UnprefixedAttribute with alternatives:
[error]   (key: String,value: Option[scala.collection.Seq[scala.xml.Node]],next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: String,next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: scala.collection.Seq[scala.xml.Node],next1: scala.xml.MetaData)scala.xml.UnprefixedAttribute
[error]  cannot be invoked with (String, org.scalajs.dom.Event => Unit, scala.xml.MetaData)
[error]         <input class="toggle" type="checkbox" checked={todo.completed} onclick={toggleHandler}/>
[error]         ^
[error] E:\pro\workspace\desu-video\target\todo\js\src\main\scala\com\thoughtworks\todo\Main.scala:101:83: value value is not a member of scala.xml.Elem
[error]         <label ondblclick={ _: Event => editingTodo.value = Some(todo); editInput.value.focus() }>{ todo.title }</label>
[error]                                                                                   ^
[error] E:\pro\workspace\desu-video\target\todo\js\src\main\scala\com\thoughtworks\todo\Main.scala:102:9: multiple constructors for UnprefixedAttribute with alternatives:
[error]   (key: String,value: Option[scala.collection.Seq[scala.xml.Node]],next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: String,next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: scala.collection.Seq[scala.xml.Node],next1: scala.xml.MetaData)scala.xml.UnprefixedAttribute
[error]  cannot be invoked with (String, org.scalajs.dom.Event => com.thoughtworks.todo.Main.Todo, scala.xml.MetaData)
[error]         <button class="destroy" onclick={ _: Event => allTodos.value.remove(allTodos.value.indexOf(todo)) }></button>
[error]         ^
[error] E:\pro\workspace\desu-video\target\todo\js\src\main\scala\com\thoughtworks\todo\Main.scala:98:5: type mismatch;
[error]  found   : scala.xml.Elem
[error]  required: com.thoughtworks.binding.Binding[org.scalajs.dom.raw.Node]
[error]     <li class={s"${if (todo.completed) "completed" else ""} ${if (editingTodo.bind.contains(todo)) "editing" else ""}"}>
[error]     ^
[error] E:\pro\workspace\desu-video\target\todo\js\src\main\scala\com\thoughtworks\todo\Main.scala:116:5: multiple constructors for UnprefixedAttribute with alternatives:
[error]   (key: String,value: Option[scala.collection.Seq[scala.xml.Node]],next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: String,next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: scala.collection.Seq[scala.xml.Node],next1: scala.xml.MetaData)scala.xml.UnprefixedAttribute
[error]  cannot be invoked with (String, org.lrng.binding.html.NodeBindingSeq[org.scalajs.dom.Node], scala.xml.MetaData
[error]     <section class="main" style={ if (allTodos.length.bind == 0) "display:none" else "" }>
[error]     ^
[error] E:\pro\workspace\desu-video\target\todo\js\src\main\scala\com\thoughtworks\todo\Main.scala:117:7: multiple constructors for UnprefixedAttribute with alternatives:
[error]   (key: String,value: Option[scala.collection.Seq[scala.xml.Node]],next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: String,next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: scala.collection.Seq[scala.xml.Node],next1: scala.xml.MetaData)scala.xml.UnprefixedAttribute
[error]  cannot be invoked with (String, org.scalajs.dom.Event => Unit, scala.xml.MetaData)
[error]       <input type="checkbox" id="toggle-all" class="toggle-all" checked={active.items.length.bind == 0} onclick={toggleAllClickHandler}/>
[error]       ^
[error] E:\pro\workspace\desu-video\target\todo\js\src\main\scala\com\thoughtworks\todo\Main.scala:118:7: multiple constructors for UnprefixedAttribute with alternatives:
[error]   (key: String,value: Option[scala.collection.Seq[scala.xml.Node]],next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: String,next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: scala.collection.Seq[scala.xml.Node],next1: scala.xml.MetaData)scala.xml.UnprefixedAttribute
[error]  cannot be invoked with (String, org.lrng.binding.html.NodeBindingSeq[org.scalajs.dom.Node], scala.xml.MetaData
[error]       <label for="toggle-all">Mark all as complete</label>
[error]       ^
[error] E:\pro\workspace\desu-video\target\todo\js\src\main\scala\com\thoughtworks\todo\Main.scala:119:7: multiple constructors for UnprefixedAttribute with alternatives:
[error]   (key: String,value: Option[scala.collection.Seq[scala.xml.Node]],next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: String,next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: scala.collection.Seq[scala.xml.Node],next1: scala.xml.MetaData)scala.xml.UnprefixedAttribute
[error]  cannot be invoked with (String, org.lrng.binding.html.NodeBindingSeq[org.scalajs.dom.Node], scala.xml.MetaData
[error]       <ul class="todo-list">{ for (todo <- route.state.bind.items) yield todoListItem(todo).bind }</ul>
[error]       ^
[error] E:\pro\workspace\desu-video\target\todo\js\src\main\scala\com\thoughtworks\todo\Main.scala:127:5: multiple constructors for UnprefixedAttribute with alternatives:
[error]   (key: String,value: Option[scala.collection.Seq[scala.xml.Node]],next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: String,next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: scala.collection.Seq[scala.xml.Node],next1: scala.xml.MetaData)scala.xml.UnprefixedAttribute
[error]  cannot be invoked with (String, org.lrng.binding.html.NodeBindingSeq[org.scalajs.dom.Node], scala.xml.MetaData
[error]     <footer class="footer" style={ if (allTodos.length.bind == 0) "display:none" else "" }>
[error]     ^
[error] E:\pro\workspace\desu-video\target\todo\js\src\main\scala\com\thoughtworks\todo\Main.scala:128:7: multiple constructors for UnprefixedAttribute with alternatives:
[error]   (key: String,value: Option[scala.collection.Seq[scala.xml.Node]],next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: String,next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: scala.collection.Seq[scala.xml.Node],next1: scala.xml.MetaData)scala.xml.UnprefixedAttribute
[error]  cannot be invoked with (String, org.lrng.binding.html.NodeBindingSeq[org.scalajs.dom.Node], scala.xml.MetaData
[error]       <span class="todo-count">
[error]       ^
[error] E:\pro\workspace\desu-video\target\todo\js\src\main\scala\com\thoughtworks\todo\Main.scala:131:7: multiple constructors for UnprefixedAttribute with alternatives:
[error]   (key: String,value: Option[scala.collection.Seq[scala.xml.Node]],next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: String,next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: scala.collection.Seq[scala.xml.Node],next1: scala.xml.MetaData)scala.xml.UnprefixedAttribute
[error]  cannot be invoked with (String, org.lrng.binding.html.NodeBindingSeq[org.scalajs.dom.Node], scala.xml.MetaData
[error]       <ul class="filters">{
[error]       ^
[error] E:\pro\workspace\desu-video\target\todo\js\src\main\scala\com\thoughtworks\todo\Main.scala:138:7: multiple constructors for UnprefixedAttribute with alternatives:
[error]   (key: String,value: Option[scala.collection.Seq[scala.xml.Node]],next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: String,next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: scala.collection.Seq[scala.xml.Node],next1: scala.xml.MetaData)scala.xml.UnprefixedAttribute
[error]  cannot be invoked with (String, org.scalajs.dom.Event => scala.collection.mutable.Buffer[com.thoughtworks.todo.Main.Todo], scala.xml.MetaData)
[error]       <button class="clear-completed" onclick={clearCompletedClickHandler}
[error]       ^
[error] E:\pro\workspace\desu-video\target\todo\js\src\main\scala\com\thoughtworks\todo\Main.scala:146:5: multiple constructors for UnprefixedAttribute with alternatives:
[error]   (key: String,value: Option[scala.collection.Seq[scala.xml.Node]],next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: String,next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: scala.collection.Seq[scala.xml.Node],next1: scala.xml.MetaData)scala.xml.UnprefixedAttribute
[error]  cannot be invoked with (String, org.lrng.binding.html.NodeBindingSeq[org.scalajs.dom.Node], scala.xml.MetaData
[error]     <section class="todoapp">{ header.bind }{ mainSection.bind }{ footer.bind }</section>
[error]     ^
[error] E:\pro\workspace\desu-video\target\todo\js\src\main\scala\com\thoughtworks\todo\Main.scala:147:5: multiple constructors for UnprefixedAttribute with alternatives:
[error]   (key: String,value: Option[scala.collection.Seq[scala.xml.Node]],next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: String,next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: scala.collection.Seq[scala.xml.Node],next1: scala.xml.MetaData)scala.xml.UnprefixedAttribute
[error]  cannot be invoked with (String, org.lrng.binding.html.NodeBindingSeq[org.scalajs.dom.Node], scala.xml.MetaData
[error]     <footer class="info">
[error]     ^
[error] E:\pro\workspace\desu-video\target\todo\js\src\main\scala\com\thoughtworks\todo\Main.scala:148:7: type mismatch
[error]  found   : org.lrng.binding.html.NodeBindingSeq[org.scalajs.dom.Node]
[error]     (which expands to)  com.thoughtworks.binding.Binding.BindingSeq[org.scalajs.dom.raw.Node]{def value: scala.collection.Seq[org.scalajs.dom.raw.Node]}
[error]  required: Seq[scala.xml.Node]
[error]       <p>Double-click to edit a todo</p>
[error]       ^
[error] E:\pro\workspace\desu-video\target\todo\js\src\main\scala\com\thoughtworks\todo\Main.scala:149:21: multiple constructors for UnprefixedAttribute with alternatives:
[error]   (key: String,value: Option[scala.collection.Seq[scala.xml.Node]],next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: String,next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: scala.collection.Seq[scala.xml.Node],next1: scala.xml.MetaData)scala.xml.UnprefixedAttribute
[error]  cannot be invoked with (String, org.lrng.binding.html.NodeBindingSeq[org.scalajs.dom.Node], scala.xml.MetaData
[error]       <p>Written by <a href="https://github.com/atry">Yang Bo</a></p>
[error]                     ^
[error] E:\pro\workspace\desu-video\target\todo\js\src\main\scala\com\thoughtworks\todo\Main.scala:150:18: multiple constructors for UnprefixedAttribute with alternatives:
[error]   (key: String,value: Option[scala.collection.Seq[scala.xml.Node]],next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: String,next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: scala.collection.Seq[scala.xml.Node],next1: scala.xml.MetaData)scala.xml.UnprefixedAttribute
[error]  cannot be invoked with (String, org.lrng.binding.html.NodeBindingSeq[org.scalajs.dom.Node], scala.xml.MetaData
[error]       <p>Part of <a href="http://todomvc.com">TodoMVC</a></p>
[error]                  ^
[error] 22 errors found
[error] (js / Compile / compileIncremental) Compilation failed
[error] Total time: 9 s, completed 2023骞?鏈?5鏃?涓嬪崍12:34:24:24
sbt:todo>

**Comment by Atry** [comment]
Could you report it to https://github.com/scala/bug ? It looks like a breaking change in Scala 2.13.9

**Comment by djx314** [comment]
> Could you report it to https://github.com/scala/bug ? It looks like a breaking change in Scala 2.13.9

I will have a try.

**Comment by Atry** [comment]
Anyway, this repository has moved to Scala 3. If there is a fix, it should be either from Scala compiler or https://github.com/GlasslabGames/nameBasedXml.scala

**Comment by Atry** [comment]
Close this issue because there is nothing to do in this repository. The issue should be tracked at https://github.com/Atry/nameBasedXml.scala/issues/2

**Comment by djx314** [comment]
> Close this issue because there is nothing to do in this repository. The issue should be tracked at [Atry/nameBasedXml.scala#2](https://github.com/Atry/nameBasedXml.scala/issues/2)

Thanks, just fix the product problem in Scala 2 is Ok. No more future request.
